import type { PortfolioPageContent } from "../lib/types";

const CDN = "https://cdn.prod.website-files.com/6682fcb4cd26b11752a185d3";

export const portfolioPage: PortfolioPageContent = {
  heading: "Some of our project highlights",
  subheading: "While it's not our full portfolio, these are our top projects",
  filterTags: [
    "All Projects",
    "AI",
    "Business",
    "Education",
    "Finance",
    "Health",
    "Lifestyle",
    "Productivity",
    "Social",
    "Video",
  ],
  items: [
    {
      slug: "clapper",
      clientName: "Clapper",
      logoSrc: "/images/logo.clapper.svg",
      logoAlt: "Clapper",
      tags: ["Social"],
      description:
        "Clapper partnered with us to bring their vision of a real community-driven social media platform to life. We developed and delivered the first version of their app, empowering users to share content, connect authentically, and engage with their audience without filters or algorithms. Our team ensured a seamless launch, laying the foundation for Clapper's growth.",
      highlights: [
        { label: "18 weeks to launch", iconSrc: "/images/portfolio-black-weeks-to-launch.svg" },
        { label: "1M+ downloads", iconSrc: "/images/portfolio-black-downloads.svg" },
      ],
      imageSrc: "/images/V12f.webp",
      imageAlt:
        "Two smartphones displaying a social media app with video feeds and category tags like #Football and #FamilyFun.",
      caseStudyHref: "/projects/casestudy/clapper",
      theme: "light",
      backgroundImage: "linear-gradient(#fff, #96b7fd73 23%)",
    },
    {
      slug: "clearcover",
      clientName: "Clearcover Car Insurance",
      logoSrc: "/images/Clearcover_logo.webp",
      logoAlt: "Clearcover",
      tags: ["Finance"],
      description:
        "We developed the Clearcover app to make managing your car insurance quick and simple. You can view policies, submit claims, make payments, and get roadside assistance—all from your phone. With Clearcover, you get better coverage, lower prices, and everything you need just a few taps away.",
      highlights: [
        { label: "8 weeks to launch", iconSrc: "/images/portfolio-black-weeks-to-launch.svg" },
        { label: "150K downloads", iconSrc: "/images/portfolio-black-downloads.svg" },
      ],
      imageSrc: "/images/Frame-Clearcover.webp",
      imageAlt: "Clearcover app screens showing car insurance policy management.",
      caseStudyHref: "/projects/casestudy/clearcover",
      theme: "light",
      backgroundImage: "linear-gradient(#fff, #cfe3ff8a 23%)",
    },
    {
      slug: "spendee",
      clientName: "Spendee",
      logoSrc: "/images/Spendee-Logo.avif",
      logoAlt: "Spendee",
      tags: ["Finance"],
      description:
        "Spendee teamed up with Synergy Labs to revitalize their popular budgeting app. We redesigned and enhanced the app's functionality, delivering a more intuitive and engaging experience for 3 million users.",
      highlights: [
        { label: "16 weeks to launch", iconSrc: "/images/portfolio-black-weeks-to-launch.svg" },
        { label: "1M downloads", iconSrc: "/images/portfolio-black-downloads.svg" },
      ],
      imageSrc: "/images/Spendee_Phones_Medium.webp",
      imageAlt: "Phones displaying the Spendee budgeting app dashboard.",
      caseStudyHref: "/projects/casestudy/spendee",
      theme: "light",
      backgroundImage: "linear-gradient(#fff, #c9f5da8a 23%)",
    },
    {
      slug: "fanbase",
      clientName: "Fanbase",
      logoSrc: `${CDN}/672566666bbf3cb8419538c9_logo_white.avif`,
      logoAlt: "Fanbase",
      tags: ["Social", "Video"],
      description:
        "We partnered with Fanbase to bring their vision of an unrestricted social creator hub to life, where users can create, share, and monetize content without ads, shadowbans, or limitations. We developed features that enable users to upload short and long-form videos, images, stories, livestreams, and audio content.",
      highlights: [
        { label: "16 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "100K+ downloads", iconSrc: "/images/portfolio-white-downloads.svg" },
      ],
      imageSrc: `${CDN}/6729333be54461fc4d7dd907_FB%20Image%20(1).avif`,
      imageAlt: "Fanbase app screens showing the creator content feed.",
      caseStudyHref: "/projects/casestudy/fanbase",
      theme: "dark",
      backgroundImage: "linear-gradient(#1b1330, #4a2e7a)",
    },
    {
      slug: "joe-and-the-juice",
      clientName: "Joe & The Juice",
      logoSrc: `${CDN}/6808f2b8933651ce7bfbd56b_unnamed%20(6).webp`,
      logoAlt: "Joe & The Juice",
      tags: ["Lifestyle"],
      description:
        "By redesigning the mobile app and providing ongoing design support, Synergy Labs helped Joe & The Juice create a modern, user-friendly experience that continues to evolve.",
      highlights: [
        { label: "8 weeks to launch", iconSrc: "/images/portfolio-black-weeks-to-launch.svg" },
        { label: "150K downloads", iconSrc: "/images/portfolio-black-downloads.svg" },
      ],
      imageSrc: `${CDN}/68120bf300f7f1d2652fe27d_Frame%201948753706-2.webp`,
      imageAlt: "Joe & The Juice app ordering screens.",
      caseStudyHref: "/projects/casestudy/joe-and-the-juice",
      theme: "light",
      backgroundImage: "linear-gradient(#fff, #ffe9c473 23%)",
    },
    {
      slug: "urban-massage",
      clientName: "Urban Massage",
      logoSrc: `${CDN}/67f67cbd7e3e2e6b6d8e2eb7_t7Sg1g8SF4knGaV8UlZTCTDvUQ8UVV29dyct7GMy_cr.avif`,
      logoAlt: "Urban Massage",
      tags: ["Lifestyle"],
      description:
        "Urban Massage engaged Synergy Labs to develop a mobile application aimed at streamlining the massage booking process and enhancing the communication between customers and therapists.",
      highlights: [
        { label: "8 weeks to launch", iconSrc: "/images/portfolio-black-weeks-to-launch.svg" },
        { label: "150K downloads", iconSrc: "/images/portfolio-black-downloads.svg" },
      ],
      imageSrc: `${CDN}/68120fe97aae3e1d54cec2bb_Frame%201948753707-3.webp`,
      imageAlt: "Urban Massage app booking flow.",
      caseStudyHref: "/projects/casestudy/urban-massage",
      theme: "light",
      backgroundImage: "linear-gradient(#fff, #ffd9d973 23%)",
    },
    {
      slug: "forbes-councils",
      clientName: "Forbes Councils",
      logoSrc: "/images/Forbes_1.avif",
      logoAlt: "Forbes Councils",
      tags: ["Business", "Education"],
      description:
        "Forbes Councils partnered with Synergy Labs to elevate their members-only app, making it faster, more intuitive. We introduced essential tools like expert panels, event access, private messaging, and group discussions.",
      highlights: [
        { label: "16 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "2K exclusive users", iconSrc: "/images/portfolio-white-people.svg" },
      ],
      imageSrc: "/images/Forbes-Image_1.avif",
      imageAlt: "Forbes Councils app screens",
      caseStudyHref: "/projects/casestudy/forbes-councils",
      theme: "dark",
      backgroundImage: "linear-gradient(#112134, #33629a)",
    },
    {
      slug: "signal",
      clientName: "Signal",
      logoSrc: "/images/Signal-Logo.avif",
      logoAlt: "Signal",
      tags: ["Business"],
      description:
        "Signal, a leader in tailored security solutions, partnered with us to create an app that streamlines on-site and remote assessments, boosting efficiency and precision as they grow.",
      highlights: [
        { label: "4 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "10x faster report generation" },
      ],
      imageSrc: "/images/Signal-Screen_1.avif",
      imageAlt: "Signal app showing an on-site security assessment.",
      caseStudyHref: "/projects/casestudy/signal",
      theme: "dark",
      backgroundImage: "linear-gradient(#0b1e33, #1f4068)",
    },
    {
      slug: "peanut",
      clientName: "Peanut",
      logoSrc: "/images/Peanut_App_Logo.svg",
      logoAlt: "Peanut",
      tags: ["Social"],
      description:
        "Peanut partnered with us to enhance their platform, providing a beautifully crafted design that resonates with their community of women seeking connection and support. We delivered a user-centered design tailored to the unique needs of their audience, while also outstaffing highly skilled developers to ensure seamless execution and implementation.",
      highlights: [
        { label: "22 weeks to launch", iconSrc: "/images/portfolio-black-weeks-to-launch.svg" },
        { label: "Over 5 million users", iconSrc: "/images/portfolio-black-downloads.svg" },
      ],
      imageSrc: "/images/peanut-app-image.webp",
      imageAlt:
        "Three smartphones displaying the Peanut app showing pregnancy week 8, supplement ad, and Needed introduction screen.",
      caseStudyHref: "/projects/casestudy/peanut",
      theme: "light",
      backgroundImage: "radial-gradient(circle at 0 0, #f3f3f3b5 23%, #fde9ea66 35%, #ea515a38 78%)",
    },
    {
      slug: "workit-health",
      clientName: "Workit Health",
      logoSrc: `${CDN}/67ebd685dd1e7be0ff2400fe_unnamed.webp`,
      logoAlt: "Workit Health",
      tags: ["Health"],
      description:
        "Workit Health is a telemedicine app offering virtual treatment for addiction and mental health, including therapy, medication, and recovery support.",
      highlights: [
        { label: "32,000+ patients served", iconSrc: "/images/portfolio-black-downloads.svg" },
        { label: "4.7+ star rating" },
      ],
      imageSrc: `${CDN}/67ebd675593945fbfb7cbc24_Group%2048095986.webp`,
      imageAlt: "Workit Health telemedicine app screens.",
      caseStudyHref: "/projects/casestudy/workit-health",
      theme: "light",
      backgroundImage: "linear-gradient(#fff, #cdf3e6 23%)",
    },
    {
      slug: "bylt-basics",
      clientName: "BYLT Basics",
      logoSrc: "/images/BYLT-Basics-logo_1.avif",
      logoAlt: "BYLT Basics",
      tags: ["Lifestyle"],
      description:
        "BYLT Premium Basics partnered with us to create a seamless shopping experience for premium basics apparel. We developed an intuitive app that makes it easy for users to browse new arrivals, access exclusive offers, and enjoy a secure, smooth checkout process.",
      highlights: [
        { label: "8 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "$1.4 million in in-app revenue" },
      ],
      imageSrc: `${CDN}/67c2fb353803e214c0164f77_Frame%201.webp`,
      imageAlt: "BYLT Basics shopping app screens.",
      caseStudyHref: "/projects/casestudy/bylt-basics",
      theme: "dark",
      backgroundImage: "linear-gradient(#000, #262626)",
    },
    {
      slug: "dose-of-colors",
      clientName: "Dose of Colors",
      logoSrc: `${CDN}/67b740942b5630a3f7417f4d_IMG_7048__1_-removebg-preview.avif`,
      logoAlt: "Dose of Colors",
      tags: ["Lifestyle"],
      description:
        "Dose of Colors partnered with us to bring their beauty store to mobile. We built a fast, easy-to-use app with an elegant design and simple, clean colors that match their brand. From browsing to checkout, everything feels smooth and effortless. In just 18 weeks, we turned their vision into reality.",
      highlights: [
        { label: "18 weeks to launch", iconSrc: "/images/portfolio-black-weeks-to-launch.svg" },
        { label: "4.9/5 average rating" },
      ],
      imageSrc: `${CDN}/67b71160e094a9fa86d01c73_Group%2048095984.webp`,
      imageAlt: "Dose of Colors beauty shopping app screens.",
      caseStudyHref: "/projects/casestudy/dose-of-colors",
      theme: "light",
      backgroundImage: "radial-gradient(circle at 0 0, #f3f3f3b5 23%, #ffe1ef66 35%, #ff5fa238 78%)",
    },
    {
      slug: "taskade",
      clientName: "Taskade - AI Agents",
      logoSrc: `${CDN}/67ec14a677da00daf0335ac0_Screenshot%202025-02-27%20at%2021.21.32.webp`,
      logoAlt: "Taskade",
      tags: ["AI", "Productivity"],
      description:
        "Taskade AI partnered with us to enhance productivity through a seamless platform that allows users to easily build, train, and deploy AI teams. We designed an intuitive, user-friendly interface to streamline workflows, automate tasks, and boost collaboration.",
      highlights: [
        { label: "16 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "4.7+ star rating" },
      ],
      imageSrc: `${CDN}/67ec139c64e2e8fe57c3b5bc_Frame%201948753702.webp`,
      imageAlt: "Taskade AI agent workflow builder screens.",
      caseStudyHref: "/projects/casestudy/taskade",
      theme: "dark",
      backgroundImage: "linear-gradient(#12121e, #2b2b52)",
    },
    {
      slug: "slowly",
      clientName: "Slowly",
      logoSrc: "/images/Slowly-White-Logo.avif",
      logoAlt: "Slowly",
      tags: ["Social"],
      description:
        "We played a key role in developing new features for the Slowly web app. In 2020, we added Dark Mode, audio note exchanges, and flexible letter handling, enhancing user experience.",
      highlights: [
        { label: "8 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "5M downloads", iconSrc: "/images/portfolio-white-downloads.svg" },
      ],
      imageSrc: "/images/Slowly_1.avif",
      imageAlt: "Slowly app showing pen-pal letter exchange screens.",
      caseStudyHref: "/projects/casestudy/slowly",
      theme: "dark",
      backgroundImage: "linear-gradient(#2b1d0e, #6b4a1e)",
    },
    {
      slug: "open",
      clientName: "Open",
      logoSrc: "/images/Open-Logo.avif",
      logoAlt: "Open Logo",
      tags: ["Health", "Lifestyle"],
      description:
        "Open partnered with us to revamp their app with a fresh design and key performance improvements, creating a smoother and more modern user experience.",
      highlights: [
        { label: "8 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "500k downloads", iconSrc: "/images/portfolio-white-downloads.svg" },
      ],
      imageSrc: "/images/Open-Iphone.avif",
      imageAlt: "iPhone screen with Open app",
      caseStudyHref: "/projects/casestudy/open",
      theme: "dark",
      backgroundImage: "linear-gradient(#000, #333)",
    },
    {
      slug: "lando-ai",
      clientName: "Lando AI",
      logoSrc: "/images/Lando-AI-1.avif",
      logoAlt: "Lando AI",
      tags: ["AI"],
      description:
        "The Lando AI team aimed to automate landing page creation. We developed AI that retrieves information and images from app stores, generating landing pages instantly.",
      highlights: [
        { label: "6 weeks to launch", iconSrc: "/images/portfolio-white-weeks-to-launch.svg" },
        { label: "100K websites generated" },
      ],
      imageSrc: "/images/LandoAI_1.avif",
      imageAlt: "Lando AI landing page generator screens.",
      caseStudyHref: "/projects/casestudy/lando-ai",
      theme: "dark",
      backgroundImage: "linear-gradient(#101820, #26405c)",
    },
  ],
};
